import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {DEVELOPER_PROMPT} from './server/ai-handler.js';
import {CALCULATION_TOOL} from './server/ai-calculations.js';
import {REPLY_SCHEMA} from './ai-contract.js';

export function generateOvhContract(){
  const data=JSON.stringify({prompt:DEVELOPER_PROMPT,tool:CALCULATION_TOOL,schema:REPLY_SCHEMA},null,2);
  const php="<?php\ndeclare(strict_types=1);\n// Generated by build-ovh.js from the shared JavaScript contract. No secrets.\nreturn json_decode(<<<'BYHNEX_CONTRACT'\n"+data+"\nBYHNEX_CONTRACT, true, 32, JSON_THROW_ON_ERROR);\n";
  fs.writeFileSync('server/ovh/api/lib/contract.php',php);
  return php;
}

// Small dependency-free ZIP writer, store method; packages only an explicit file list.
function zip(entries){
  const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
  const local=[],central=[];let offset=0;
  for(const [filename,data] of entries){
    const name=Buffer.from(filename),body=Buffer.from(data);let crc=0xffffffff;
    for(const byte of body)crc=table[(crc^byte)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;
    const header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50,0);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(0x5d43,12);header.writeUInt32LE(crc,14);header.writeUInt32LE(body.length,18);header.writeUInt32LE(body.length,22);header.writeUInt16LE(name.length,26);
    const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50,0);directory.writeUInt16LE(20,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt16LE(0x5d43,14);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(body.length,20);directory.writeUInt32LE(body.length,24);directory.writeUInt16LE(name.length,28);directory.writeUInt32LE(offset,42);
    local.push(header,name,body);central.push(directory,name);offset+=header.length+name.length+body.length;
  }
  const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);
  return Buffer.concat([...local,directory,end]);
}

export function buildOvh(){
  generateOvhContract();
  const files=['api/.htaccess','api/ai-chat.php','api/lib/.htaccess','api/lib/settings.php','api/lib/context.php','api/lib/calculations.php','api/lib/backend.php','api/lib/contract.php'];
  const entries=[];
  for(const file of files){
    const data=fs.readFileSync(path.join('server/ovh',file),'utf8').replace(/\r\n/g,'\n');
    if(/sk-(?:proj-)?[A-Za-z0-9_-]{20,}|OPENAI_API_KEY\s*=/.test(data))throw Error('Secret possible dans un fichier OVH.');
    const target=path.join('ovh-upload',file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data);entries.push([file,data]);
  }
  fs.writeFileSync('byhnex-ovh-api.zip',zip(entries));
  console.log('API PHP prête : ovh-upload/api/ → /www/api/ (8 fichiers, aucun .env). Archive : byhnex-ovh-api.zip');
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===path.resolve(process.argv[1]))buildOvh();
