export const TIMEFRAMES={'1m':60,'5m':300,'15m':900,'30m':1800,'1H':3600,'4H':14400,'1D':86400,'1W':604800};
export function bucketTime(time,seconds){const shift=seconds===604800?345600000:0;return Math.floor((time-shift)/(seconds*1000))*seconds*1000+shift;}
export function normalizeCandles(rows,provider){
  const data=rows.map(r=>provider==='Coinbase'?{time:Number(r[0])*1000,low:+r[1],high:+r[2],open:+r[3],close:+r[4],volume:+r[5]}:{time:+r[0],open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]});
  return [...new Map(data.filter(c=>Object.values(c).every(Number.isFinite)&&c.open>0&&c.close>0&&c.low>0&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close)&&c.volume>=0).map(c=>[c.time,c])).values()].sort((a,b)=>a.time-b.time);
}
export function aggregateCandles(data,seconds){const buckets=new Map();for(const c of [...data].sort((a,b)=>a.time-b.time)){const t=bucketTime(c.time,seconds),previous=buckets.get(t);if(previous){previous.high=Math.max(previous.high,c.high);previous.low=Math.min(previous.low,c.low);previous.close=c.close;previous.volume+=c.volume;}else buckets.set(t,{...c,time:t});}return [...buckets.values()];}
export function applyTrade(data,trade,seconds){const t=bucketTime(trade.time,seconds),last=data.at(-1);if(!Number.isFinite(trade.price)||trade.price<=0||!Number.isFinite(trade.time))return data;if(last&&t<last.time)return data;const volume=Number.isFinite(trade.size)&&trade.size>0?trade.size:0;if(last&&t===last.time){last.high=Math.max(last.high,trade.price);last.low=Math.min(last.low,trade.price);last.close=trade.price;last.volume+=volume;}else data.push({time:t,open:trade.price,high:trade.price,low:trade.price,close:trade.price,volume});return data;}
const binanceIntervals={'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1H':'1h','4H':'4h','1D':'1d','1W':'1w'};
export class LiveMarket extends EventTarget{
  constructor({fetcher=globalThis.fetch,socketClass=globalThis.WebSocket,now=()=>Date.now()}={}){super();this.fetcher=fetcher;this.Socket=socketClass;this.now=now;this.asset='SOL';this.timeframe='1H';this.provider='Coinbase';this.quote='USD';this.quotes={};this.series=new Map();this.nativeSeries=new Map();this.generation=0;this.status='loading';this.lastUpdate=0;this.closed=false;this.retry=0;this.seenTrades=new Map();}
  emit(){this.dispatchEvent(new Event('update'));}
  get key(){return `${this.provider}:${this.asset}:${this.timeframe}`;}
  get candles(){return this.series.get(this.key)||[];}
  get fresh(){return !this.closed&&!'stale unavailable loading'.split(' ').includes(this.status)&&this.now()-this.lastUpdate<90000&&['SOL','BTC'].every(a=>this.quotes[a]?.price>0)&&this.candles.length>0;}
  async json(url){const response=await this.fetcher.call(globalThis,url,{signal:AbortSignal.timeout(7000)});if(!response.ok)throw Error(`HTTP ${response.status}`);return response.json();}
  async start(asset='SOL',timeframe='1H'){this.asset=asset;this.timeframe=timeframe;this.closed=false;this.status='loading';this.emit();await this.refresh(true);if(!this.closed){this.connect();this.poll=setInterval(()=>this.refresh(),30000);this.health=setInterval(()=>{if(this.now()-this.lastUpdate>90000){this.status='stale';this.emit();}},10000);}}
  async refresh(allowFallback=false){if(this.refreshing)return;this.refreshing=true;const generation=this.generation,provider=this.provider;try{await Promise.all([this.loadQuotes(provider,generation),this.loadCandles(provider,generation)]);if(generation===this.generation){this.lastUpdate=this.now();this.status=this.socket?.readyState===1?'live':'polling';this.emit();}}catch(error){if(generation===this.generation){this.error=error.message;this.status=this.lastUpdate?'stale':'unavailable';this.emit();if(allowFallback&&provider==='Coinbase'){this.provider='Binance';this.quote='USDT';this.quotes={};this.refreshing=false;return this.refresh(false);}}}finally{this.refreshing=false;}}
  async loadQuotes(provider,generation){let quotes={};if(provider==='Coinbase'){const results=await Promise.all(['SOL','BTC'].map(async a=>{const [ticker,stats]=await Promise.all([this.json(`https://api.exchange.coinbase.com/products/${a}-USD/ticker`),this.json(`https://api.exchange.coinbase.com/products/${a}-USD/stats`)]);const price=+ticker.price;if(!(price>0)||!(+stats.open>0))throw Error('Cours Coinbase invalide');return [a,{price,change:(price/+stats.open-1)*100,time:Date.parse(ticker.time)||this.now()}];}));quotes=Object.fromEntries(results);}else{const rows=await this.json('https://data-api.binance.vision/api/v3/ticker/24hr?symbols='+encodeURIComponent('["SOLUSDT","BTCUSDT"]'));for(const r of rows){const a=r.symbol.replace('USDT','');if(!(Number(r.lastPrice)>0))throw Error('Cours Binance invalide');quotes[a]={price:+r.lastPrice,change:+r.priceChangePercent,time:+r.closeTime};}}
    if(generation===this.generation&&provider===this.provider){this.quotes=quotes;this.emit();}}
  async loadCandles(provider,generation){const asset=this.asset,tf=this.timeframe;let data;if(provider==='Coinbase'){const seconds=TIMEFRAMES[tf],native=[60,300,900,3600,21600,86400].filter(s=>s<=seconds).at(-1),key=`${provider}:${asset}:${tf}`;const rows=await this.json(`https://api.exchange.coinbase.com/products/${asset}-USD/candles?granularity=${native}`);const rawKey=asset+':'+native,raw=[...new Map([...(this.nativeSeries.get(rawKey)||[]),...normalizeCandles(rows,provider)].map(c=>[c.time,c])).values()].sort((a,b)=>a.time-b.time);if(generation===this.generation)this.nativeSeries.set(rawKey,raw);data=aggregateCandles(raw,seconds);const previous=this.series.get(key)||[];data=[...new Map([...previous,...data].map(c=>[c.time,c])).values()].sort((a,b)=>a.time-b.time);}else{const rows=await this.json(`https://data-api.binance.vision/api/v3/klines?symbol=${asset}USDT&interval=${binanceIntervals[tf]}&limit=700`);data=normalizeCandles(rows,provider);}if(data.length<2)throw Error('Historique indisponible');if(generation===this.generation&&provider===this.provider){this.series.set(`${provider}:${asset}:${tf}`,data);this.emit();}}
  async select(asset,timeframe){if(!TIMEFRAMES[timeframe]||!['SOL','BTC'].includes(asset))throw Error('Actif ou unité invalide');this.asset=asset;this.timeframe=timeframe;this.generation++;const generation=this.generation;this.status='loading';this.disconnectSocket();this.emit();try{await this.loadCandles(this.provider,generation);if(generation===this.generation){this.status=this.now()-this.lastUpdate<90000?'polling':'stale';this.connect();this.emit();}}catch(e){if(generation===this.generation){this.status='unavailable';this.error=e.message;this.emit();this.connect();}}}
  disconnectSocket(){clearTimeout(this.reconnectTimer);clearTimeout(this.handshake);if(this.socket){this.socket.onclose=null;this.socket.onerror=null;this.socket.onmessage=null;this.socket.close();this.socket=null;}}
  connect(){if(this.closed)return;this.disconnectSocket();const provider=this.provider,generation=this.generation;try{const streams=['solusdt@ticker','btcusdt@ticker',`${this.asset.toLowerCase()}usdt@kline_${binanceIntervals[this.timeframe]}`];const socket=this.socket=new this.Socket(provider==='Coinbase'?'wss://ws-feed.exchange.coinbase.com':'wss://data-stream.binance.vision/stream?streams='+streams.join('/'));this.handshake=setTimeout(()=>{if(socket.readyState!==1)socket.close();},12000);socket.onopen=()=>{clearTimeout(this.handshake);this.retry=0;if(provider==='Coinbase')socket.send(JSON.stringify({type:'subscribe',product_ids:['SOL-USD','BTC-USD'],channels:['ticker','heartbeat']}));};socket.onmessage=e=>{if(generation!==this.generation||provider!==this.provider)return;try{const payload=JSON.parse(e.data),m=payload.data||payload;if(provider==='Coinbase'){if(m.type!=='ticker'||!['SOL-USD','BTC-USD'].includes(m.product_id)||!(+m.price>0))return;const a=m.product_id.split('-')[0],time=Date.parse(m.time)||this.now();this.quotes[a]={price:+m.price,change:+m.open_24h>0?(+m.price/+m.open_24h-1)*100:this.quotes[a]?.change||0,time};if(a===this.asset&&m.trade_id!==this.seenTrades.get(a)&&this.candles.length){this.seenTrades.set(a,m.trade_id);applyTrade(this.candles,{price:+m.price,time,size:+m.last_size},TIMEFRAMES[this.timeframe]);}}else if(m.e==='24hrTicker'){this.quotes[m.s.replace('USDT','')]={price:+m.c,change:+m.P,time:+m.E};}else if(m.e==='kline'&&m.s===this.asset+'USDT'){const c=normalizeCandles([[m.k.t,m.k.o,m.k.h,m.k.l,m.k.c,m.k.v]],'Binance')[0];if(c){const data=this.candles,index=data.findIndex(x=>x.time===c.time);if(index>=0)data[index]=c;else if(!data.length||c.time>data.at(-1).time)data.push(c);}}else return;this.lastUpdate=this.now();this.status='live';this.emit();}catch{}};const reconnect=()=>{if(this.closed||generation!==this.generation)return;this.status=this.fresh?'polling':this.lastUpdate?'stale':'unavailable';this.emit();clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>{this.refresh();this.connect();},Math.min(30000,1000*2**Math.min(this.retry++,5)));};socket.onclose=reconnect;socket.onerror=()=>socket.close();}catch{this.status='polling';this.emit();}}
  async loadMore(){const generation=this.generation,provider=this.provider,first=this.candles[0];if(!first)return;const asset=this.asset,tf=this.timeframe;let data;if(provider==='Coinbase'){const native=[60,300,900,3600,21600,86400].filter(s=>s<=TIMEFRAMES[tf]).at(-1);const end=new Date(first.time).toISOString(),start=new Date(first.time-native*299000).toISOString();const rows=await this.json(`https://api.exchange.coinbase.com/products/${asset}-USD/candles?granularity=${native}&start=${start}&end=${end}`);const rawKey=asset+':'+native,raw=[...new Map([...normalizeCandles(rows,provider),...(this.nativeSeries.get(rawKey)||[])].map(c=>[c.time,c])).values()].sort((a,b)=>a.time-b.time);if(generation===this.generation)this.nativeSeries.set(rawKey,raw);data=aggregateCandles(raw,TIMEFRAMES[tf]);}else{const rows=await this.json(`https://data-api.binance.vision/api/v3/klines?symbol=${asset}USDT&interval=${binanceIntervals[tf]}&endTime=${first.time-1}&limit=700`);data=normalizeCandles(rows,provider);}if(generation===this.generation&&provider===this.provider){this.series.set(this.key,[...new Map([...this.candles,...data].map(c=>[c.time,c])).values()].sort((a,b)=>a.time-b.time));this.emit();}}
  close(){this.closed=true;this.generation++;clearInterval(this.poll);clearInterval(this.health);this.disconnectSocket();}
}
